# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.1
  
jobs:
  cloc:
    # machine:
    #   image: ubuntu-2204:2022.04.2
    # steps:
    #   - run: |
    #       ls
    #       docker pull aldanial/cloc
    #       docker run --rm -v $PWD:/tmp aldanial/cloc 
    docker:
      - image: "aldanial/cloc"
    steps:
      - run: 
          command: |
           git clone https://github.com/Raffique-RD/testsonic.git 
           aldanial/cloc testsonic/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  cloc:
    jobs:
      - cloc

  owasp:
    jobs:
      - owasp/commandline_owasp_dependency_check:
          arguments: >-
            --scan ./ --failOnCVSS 7 
          context: global
  email:
    jobs:
      - email/send:
          body: 'Configure this notification at https://www.cinotify.cc/'
          subject: 'CircleCI job started'
          to: 'raffiquemuir@gmail.com'
