version: 2.1

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

jobs:
  run_owasp_cloc_email:
    docker:
      - image: ubuntu-2204:2022.04.2 
    steps:
      - checkout
      - run:
          command: |
            docker pull aldanial/cloc
            ls



workflows:
  build-and-send-report:
    jobs:
      - run_owasp_cloc_email


      