version: 2.1
jobs:
  report-sender:
    machine:
      image: "ubuntu-2004:current"
    steps:
      - checkout
      - run: |
          ls
          docker pull aldanial/cloc
          docker pull owasp/dependency-check
          docker run --rm -v $PWD:/tmp aldanial/cloc /tmp
          ls 
workflows:
  tasks:
    jobs:
      - report-sender
