# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  owasp: entur/owasp@0.0.18
  mailer-orb: 'sudiptog81/mailer-orb@1.0.0'
  #email: cinotify/email@1.2.0
  
jobs:
  cloc:
    # machine:
    #   image: ubuntu-2204:2022.04.2
    # steps:
    #   - run: |
    #       git clone https://github.com/Raffique-RD/testsonic.git
    #       cd testsonic
    #       docker pull aldanial/cloc
    #       docker run --rm -v $PWD:/tmp aldanial/cloc /tmp
    docker:
      - image: "aldanial/cloc"
    steps:
      - run: 
          command: |
           cd /tmp
           git clone https://github.com/Raffique-RD/testsonic.git 
           ls
           /usr/src/cloc testsonic

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  cloc:
    jobs:
      - cloc

  owasp:
    jobs:
      - owasp/commandline_owasp_dependency_check:
          arguments: >-
            --scan ./ --failOnCVSS 7 
          context: global
          
  use-my-orb:
    jobs:
      - mailer-orb/mail:
          body: |
            Sample Mail
            Regards,
            Circle CI
          from: softwaresecuredtelemetry@gmail
          subject: Test 
          to: raffiquemuir@yahoo.com
  # email:
  #   jobs:
  #     - email/send:
  #         body: 'Testing use of CINotify'
  #         subject: Testing purposes
  #         to: raffiquemuir@yahoo.com