#./owasp/dependency-check/bin/dependency-check.sh
#            --scan ./

version: 2.1

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

jobs:
  run_owasp_cloc_email:
    docker:
      - image: owasp/dependency-check
    steps:
      - checkout
      - run:
          command: |
            /usr/share/dependency-check/bin/./dependency-check.sh --scan ./ -o ./ -f "JSON"
            ls
            owasp=`cat dependency-check-report.json`
            curl --request POST 'https://www.cinotify.cc/api/notify' -d "to=raffiquemuir@yahoo.com&subject=building main&body=$owasp"




workflows:
  build-and-send-report:
    jobs:
      - run_owasp_cloc_email


      