version: 2.1

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

jobs:
  run_cloc:
    docker:
      - image: aldanial/cloc:latest
    steps:
      - run:
          command: cloc . --out=cloc.txt
      - persist_to_workspace:
          root: .
          paths: 
            - cloc.txt
    environment:
      CLOC: cloc.txt


workflows:
  build-and-send-report:
    jobs:
      - run_cloc
      - owasp/commandline_owasp_dependency_check:
          arguments: >-
            --scan ./ --failOnCVSS 7 
          context: global
      - email/send:
          subject: Testing purposes
          to: raffiquemuir@yahoo.com
          body: 'Testing use of CINotify $(CLOC)'

      