version: 2.1

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

jobs:
  run_owasp_cloc_email:
    docker:
      - image: aldanial/cloc
    steps:
      - checkout
      - run:
          command: |
            /usr/src/cloc ./



workflows:
  build-and-send-report:
    jobs:
      - run_owasp_cloc_email


      