version: 2.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

 
jobs:
  cloc:
    docker:
      - image: "aldanial/cloc"
    steps:
      - checkout
      - run:
          command: |
           /usr/src/cloc ./ --out=cloc.txt\
      - store_artifacts:
          path: cloc.txt
      - run: | 
          echo "export CLOC_URL=https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/cloc.txt" >> $BASH_ENV
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env

  email:
    docker:
      - image: cimg/base:2023.01
    steps:
      - attach_workspace:
          at: .
      - run: |
          cat bash.env > $BASH_ENV
      - email/send:
          body: |
            'Testing use of CINotify'

            **LINK FOR COUNTING LINES OF CODE (CLOC)**
            << parameters.CLOC_URL >>
            
            **LINK FOR OWASP DEPENDENCY CHECK (OWASP)**
          subject: Testing purposes
          to: raffiquemuir@yahoo.com

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  report:
    jobs:
      - cloc
      - email:
          requires:
            - cloc            


