version: 2.1
jobs:
  report-sender:
    machine:
      image: "ubuntu-2004:current"
    steps:
      - run: |
          ls
          docker pull aldanial/cloc
          docker pull owasp/dependency-check
workflows:
  tasks:
    jobs:
      - report-sender
