version: 2.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

 
jobs:
  cloc:
    docker:
      - image: "aldanial/cloc"
    steps:
      - checkout
      - run:
          command: |
           /usr/src/cloc ./ --out=cloc.txt\
      - store_artifacts:
          path: cloc.txt
      - run:
          environment:
            CIRCLE_ARTIFACT_DOMAIN: output.circle-artifacts.com
          command: |
            echo "https://${CIRCLE_ARTIFACT_DOMAIN}/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/cloc.txt"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  cloc:
    jobs:
      - cloc

  owasp:
    jobs:
      - owasp/commandline_owasp_dependency_check:
          persist_to_workspace: true
          arguments: >-
            --scan ./ --failOnCVSS 7
          context: global              

  email:
    jobs:
      - email/send:
          body: 'Testing use of CINotify'
          subject: Testing purposes
          to: raffiquemuir@yahoo.com

