#./owasp/dependency-check/bin/dependency-check.sh
#            --scan ./

version: 2.1

orbs:
  owasp: entur/owasp@0.0.18
  email: cinotify/email@1.2.0

jobs:
  run_owasp_cloc_email:
    docker:
      - image: owasp/dependency-check
    steps:
      - checkout
      - run:
          command: |
            cd /
            cd bin
            ls
            ./usr/share/dependency-check/bin/dependency-check.sh --scan ./




workflows:
  build-and-send-report:
    jobs:
      - run_owasp_cloc_email


      